# Site settings
title: Ernest Awoonor-Williams
email: esaw83@mun.ca
description: Hello
baseurl: ""
url: "http://awoonor.github.io"

author:
  name     : 'Ernest Awoonor-Williams'
  email    : esaw83@mun.ca
  url      : http://awoonor.github.io
  facebook :
  twitter  : http://twitter.com/Ernie_Willis
  linkedin  : http://ca.linkedin.com/in/eawoonorwilliams
  researchgate: https://www.researchgate.net/profile/Ernest_Awoonor-Williams
  googlescholar: https://scholar.google.com/citations?user=AwvMTjIAAAAJ&hl=en

github: https://github.com/awoonor
disqus_shortname: "ernesto"
google_analytics: UA-101112905-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
