# Site settings
title: Ernest Awoonor-Williams
email: zetsu@domain.com
description: HEllo
baseurl: ""
url: "http://nandomoreira.me"

author:
  name     : 'Ernest Awoonor-Williams'
  email    : aasdasd@asdasd.com
  url      : http://nandomoreira.me
  facebook :
  twitter  : http://twitter.com/Ernie_Willis
  linkedin  : http://ca.linkedin.com/in/eawoonorwilliams

github: https://github.com/nandomoreirame/zetsu
disqus_shortname: "fernandomoreira"
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
